import type { WidgetCardProps } from "widgets/BaseWidget";

/**
 * Package JSON 파일의 전체 구조
 */
export interface PackageJSON {
  artifactJsonType: "PACKAGE";
  clientSchemaVersion: number;
  serverSchemaVersion: number;
  exportedPackage: ExportedPackage;
  datasourceList: DatasourceConfig[];
  moduleList: ModuleConfig[];
  actionList: ActionConfig[];
  actionCollectionList: ActionCollectionConfig[];
}

/**
 * 패키지 정보
 */
export interface ExportedPackage {
  packageUUID: string;
  type: "UI" | "QUERY" | "JS";
  unpublishedPackage: {
    name: string;
    icon: string;
    color: string;
  };
  deleted: boolean;
}

/**
 * 데이터소스 설정
 */
export interface DatasourceConfig {
  datasourceConfiguration: {
    connection: {
      mode: string;
      ssl: { authType: string };
    };
    endpoints: Array<{ host: string; port: number }>;
  };
  name: string;
  pluginId: string;
  messages: string[];
  isAutoGenerated: boolean;
  isTemplate: boolean;
  gitSyncId: string;
  deleted: boolean;
}

/**
 * 모듈 설정
 */
export interface ModuleConfig {
  type: "UI_MODULE" | "QUERY_MODULE" | "JS_MODULE";
  moduleUUID: string;
  unpublishedModule: {
    name: string;
    inputsForm: ModuleInputSection[];
    outputsForm: ModuleOutputSection[];
    layouts: ModuleLayout[];
  };
  gitSyncId: string;
  deleted: boolean;
}

export interface ModuleInputSection {
  id: string;
  sectionName: string;
  children: unknown[];
}

export interface ModuleOutputSection {
  id: string;
  sectionName: string;
  children: unknown[];
}

export interface ModuleLayout {
  viewMode: boolean;
  dsl: ModuleDSL;
  layoutOnLoadActions: LayoutOnLoadAction[][];
  layoutOnLoadActionErrors: unknown[];
  validOnPageLoadActions: boolean;
  id: string;
  deleted: boolean;
  policies: unknown[];
  userPermissions: unknown[];
}

/**
 * 모듈 DSL (위젯 트리)
 */
export interface ModuleDSL {
  widgetName: string;
  type: string;
  widgetId: string;
  children?: ModuleDSL[];
  [key: string]: unknown;
}

export interface LayoutOnLoadAction {
  id: string;
  name: string;
  confirmBeforeExecute: boolean;
  pluginType: string;
  jsonPathKeys: string[];
  timeoutInMillisecond: number;
}

/**
 * 액션 설정 (Query, JS 함수 등)
 */
export interface ActionConfig {
  isPublic: boolean;
  pluginType: "DB" | "JS";
  pluginId: string;
  unpublishedAction: {
    moduleId: string;
    name: string;
    fullyQualifiedName?: string;
    datasource: {
      name: string;
      pluginId: string;
      messages: string[];
      isAutoGenerated: boolean;
      id?: string;
      deleted: boolean;
      policyMap: Record<string, unknown>;
      policies: unknown[];
      userPermissions: unknown[];
    };
    contextType: "MODULE";
    collectionId?: string;
    actionConfiguration: {
      timeoutInMillisecond: number;
      paginationType: string;
      encodeParamsToggle: boolean;
      body: string;
      selfReferencingDataPaths: string[];
      pluginSpecifiedTemplates?: Array<{ value: boolean }>;
      jsArguments?: unknown[];
    };
    runBehaviour: "AUTOMATIC" | "MANUAL";
    dynamicBindingPathList: Array<{ key: string }>;
    isValid: boolean;
    invalids: string[];
    messages: string[];
    jsonPathKeys: string[];
    userSetOnLoad: boolean;
    confirmBeforeExecute: boolean;
    policyMap: Record<string, unknown>;
    userPermissions: unknown[];
    createdAt: string;
  };
  publishedAction: {
    messages: string[];
    userSetOnLoad: boolean;
    confirmBeforeExecute: boolean;
    policyMap: Record<string, unknown>;
    userPermissions: unknown[];
  };
  gitSyncId: string;
  id: string;
  deleted: boolean;
}

/**
 * JS Object 컬렉션 설정
 */
export interface ActionCollectionConfig {
  isPublic: boolean;
  unpublishedCollection: {
    moduleId: string;
    name: string;
    contextType: "MODULE";
    pluginId: string;
    pluginType: "JS";
    actions: unknown[];
    archivedActions: unknown[];
    body: string;
    variables: unknown[];
    userPermissions: unknown[];
  };
  gitSyncId: string;
  id: string;
  deleted: boolean;
}

/**
 * UI 사이드바에 표시될 모듈 카드 (WidgetCardProps 확장)
 */
export interface PackageModuleCard extends WidgetCardProps {
  moduleUUID: string;
  packageUUID: string;
  packageName: string;
  moduleName: string;
  moduleType: "UI_MODULE" | "QUERY_MODULE" | "JS_MODULE";
  dsl: ModuleDSL;
  actions: ActionConfig[];
  actionCollections: ActionCollectionConfig[];
  datasources: DatasourceConfig[];
}

/**
 * 패키지별로 그룹화된 모듈 목록
 */
export interface PackageGroup {
  packageUUID: string;
  packageName: string;
  packageIcon: string;
  packageColor: string;
  modules: PackageModuleCard[];
}

/**
 * 모듈 인스턴스 (캔버스에 배치된 모듈)
 */
export interface ModuleInstance {
  instanceId: string;
  moduleUUID: string;
  packageUUID: string;
  moduleName: string;
  dsl: ModuleDSL;
  actions: ActionConfig[];
  actionCollections: ActionCollectionConfig[];
  isReadOnly: boolean;
}

/**
 * 모듈 위젯 타입 상수
 */
export const PACKAGE_MODULE_WIDGET_TYPE = "PACKAGE_MODULE_WIDGET";

/**
 * 기본 모듈 카드 속성
 */
export const DEFAULT_MODULE_CARD_PROPS = {
  rows: 40,
  columns: 24,
  icon: "package",
} as const;
