import type { WidgetCardProps } from "widgets/BaseWidget";

/**
 * Package JSON 파일의 전체 구조
 */
export interface PackageJSON {
  artifactJsonType: "PACKAGE";
  clientSchemaVersion: number;
  serverSchemaVersion: number;
  exportedPackage: ExportedPackage;
  datasourceList: DatasourceConfig[];
  moduleList: ModuleConfig[];
  actionList: ActionConfig[];
  actionCollectionList: ActionCollectionConfig[];
}

/**
 * 패키지 정보
 */
export interface ExportedPackage {
  packageUUID: string;
  type: "UI" | "QUERY" | "JS";
  unpublishedPackage: {
    name: string;
    icon: string;
    color: string;
  };
  deleted: boolean;
}

/**
 * 데이터소스 설정
 */
export interface DatasourceConfig {
  datasourceConfiguration: {
    connection: {
      mode: string;
      ssl: { authType: string };
    };
    endpoints: Array<{ host: string; port: number }>;
  };
  name: string;
  pluginId: string;
  messages: string[];
  isAutoGenerated: boolean;
  isTemplate: boolean;
  gitSyncId: string;
  deleted: boolean;
}

/**
 * 모듈 설정
 */
export interface ModuleConfig {
  type: "UI_MODULE" | "QUERY_MODULE" | "JS_MODULE";
  moduleUUID: string;
  unpublishedModule: {
    name: string;
    inputsForm: ModuleInputSection[];
    outputsForm: ModuleOutputSection[];
    layouts: ModuleLayout[];
  };
  gitSyncId: string;
  deleted: boolean;
}

/**
 * 모듈 Input 정의
 * 페이지에서 모듈에 전달하는 파라미터
 *
 * 실제 JSON 구조:
 * {
 *   "id": "bzkrhnmnap",
 *   "label": "defaultSelected",  // input 이름
 *   "propertyName": "inputs.defaultSelected",
 *   "controlType": "INPUT_TEXT",
 *   "defaultValue": "[]"
 * }
 */
export interface ModuleInputDefinition {
  id: string;
  label: string; // input 이름 (예: "defaultSelected", "label", "disabled")
  name?: string; // 대체 이름 필드 (호환성)
  propertyName?: string; // "inputs.defaultSelected" 형태
  controlType?: string; // "INPUT_TEXT", "SWITCH" 등
  defaultValue: unknown;
  type?: "string" | "number" | "boolean" | "array" | "object";
}

export interface ModuleInputSection {
  id: string;
  sectionName: string;
  children: ModuleInputDefinition[];
}

/**
 * 모듈 Output 정의
 * 모듈에서 페이지로 노출하는 데이터
 *
 * 실제 JSON 구조:
 * {
 *   "id": "kjtucgtyfb",
 *   "label": "selectedMember",  // output 이름
 *   "propertyName": "outputs.selectedMember",
 *   "value": "{{MultiSelect1.selectedOptionValues}}"
 * }
 */
export interface ModuleOutputDefinition {
  id: string;
  label: string; // output 이름
  name?: string; // 대체 이름 필드 (호환성)
  propertyName?: string; // "outputs.selectedMember" 형태
  value: string; // 바인딩 표현식, 예: "{{MultiSelect1.selectedOptionValues}}"
}

export interface ModuleOutputSection {
  id: string;
  sectionName: string;
  children: ModuleOutputDefinition[];
}

/**
 * 모듈 인스턴스의 Input/Output 런타임 값
 */
export interface ModuleInstanceInputs {
  [inputName: string]: unknown;
}

export interface ModuleInstanceOutputs {
  [outputName: string]: unknown;
}

export interface ModuleLayout {
  viewMode: boolean;
  dsl: ModuleDSL;
  layoutOnLoadActions: LayoutOnLoadAction[][];
  layoutOnLoadActionErrors: unknown[];
  validOnPageLoadActions: boolean;
  id: string;
  deleted: boolean;
  policies: unknown[];
  userPermissions: unknown[];
}

/**
 * 모듈 DSL (위젯 트리)
 */
export interface ModuleDSL {
  widgetName: string;
  type: string;
  widgetId: string;
  children?: ModuleDSL[];
  [key: string]: unknown;
}

export interface LayoutOnLoadAction {
  id: string;
  name: string;
  confirmBeforeExecute: boolean;
  pluginType: string;
  jsonPathKeys: string[];
  timeoutInMillisecond: number;
}

/**
 * 액션 설정 (Query, JS 함수 등)
 */
export interface ActionConfig {
  isPublic: boolean;
  pluginType: "DB" | "JS" | "SAAS";
  pluginId: string;
  // runBehaviour는 action 루트 레벨에도 있을 수 있음 (JSON 구조)
  runBehaviour?: "AUTOMATIC" | "MANUAL" | "ON_PAGE_LOAD";
  unpublishedAction: {
    moduleId: string;
    name: string;
    fullyQualifiedName?: string;
    datasource: {
      name: string;
      pluginId: string;
      messages: string[];
      isAutoGenerated: boolean;
      id?: string;
      deleted: boolean;
      policyMap: Record<string, unknown>;
      policies: unknown[];
      userPermissions: unknown[];
    };
    contextType: "MODULE";
    collectionId?: string;
    actionConfiguration: {
      timeoutInMillisecond: number;
      paginationType: string;
      encodeParamsToggle: boolean;
      body: string;
      selfReferencingDataPaths: string[];
      pluginSpecifiedTemplates?: Array<{ value: boolean }>;
      jsArguments?: unknown[];
      formData?: Record<string, unknown>;
    };
    runBehaviour: "AUTOMATIC" | "MANUAL" | "ON_PAGE_LOAD";
    dynamicBindingPathList: Array<{ key: string }>;
    isValid: boolean;
    invalids: string[];
    messages: string[];
    jsonPathKeys: string[];
    userSetOnLoad: boolean;
    confirmBeforeExecute: boolean;
    policyMap: Record<string, unknown>;
    userPermissions: unknown[];
    createdAt: string;
  };
  publishedAction: {
    messages: string[];
    userSetOnLoad: boolean;
    confirmBeforeExecute: boolean;
    policyMap: Record<string, unknown>;
    userPermissions: unknown[];
  };
  gitSyncId: string;
  id: string;
  deleted: boolean;
}

/**
 * JS Object 컬렉션 설정
 */
export interface ActionCollectionConfig {
  isPublic: boolean;
  unpublishedCollection: {
    moduleId: string;
    name: string;
    contextType: "MODULE";
    pluginId: string;
    pluginType: "JS";
    actions: unknown[];
    archivedActions: unknown[];
    body: string;
    variables: unknown[];
    userPermissions: unknown[];
  };
  gitSyncId: string;
  id: string;
  deleted: boolean;
}

/**
 * UI 사이드바에 표시될 모듈 카드 (WidgetCardProps 확장)
 */
export interface PackageModuleCard extends WidgetCardProps {
  moduleUUID: string;
  packageUUID: string;
  packageName: string;
  moduleName: string;
  moduleType: "UI_MODULE" | "QUERY_MODULE" | "JS_MODULE";
  dsl: ModuleDSL;
  actions: ActionConfig[];
  actionCollections: ActionCollectionConfig[];
  datasources: DatasourceConfig[];
  // Input/Output 정의
  inputsForm?: ModuleInputSection[];
  outputsForm?: ModuleOutputSection[];
}

/**
 * 패키지별로 그룹화된 모듈 목록
 */
export interface PackageGroup {
  packageUUID: string;
  packageName: string;
  packageIcon: string;
  packageColor: string;
  modules: PackageModuleCard[];
}

/**
 * 모듈 인스턴스 (캔버스에 배치된 모듈)
 */
export interface ModuleInstance {
  instanceId: string;
  moduleUUID: string;
  packageUUID: string;
  moduleName: string;
  dsl: ModuleDSL;
  actions: ActionConfig[];
  actionCollections: ActionCollectionConfig[];
  isReadOnly: boolean;
  // Input/Output 정의
  inputsForm?: ModuleInputSection[];
  outputsForm?: ModuleOutputSection[];
  // 런타임 Input/Output 값
  inputs?: ModuleInstanceInputs;
  outputs?: ModuleInstanceOutputs;
}

/**
 * 모듈 위젯 타입 상수
 */
export const PACKAGE_MODULE_WIDGET_TYPE = "PACKAGE_MODULE_WIDGET";

/**
 * 기본 모듈 카드 속성
 */
export const DEFAULT_MODULE_CARD_PROPS = {
  rows: 40,
  columns: 24,
  icon: "package",
} as const;

// ============================================================================
// 새 모듈 시스템 타입 정의
// ============================================================================

/**
 * 새 구조: 참조 + 인스턴스 데이터만 저장
 *
 * 페이지 DSL에 저장되는 최소 데이터입니다.
 * 공통 데이터(레이아웃, 코드, 스키마)는 ModuleRegistry에서 조회합니다.
 */
export interface ModuleWidgetPropsNew {
  // 위젯 기본 속성
  widgetId: string;
  widgetName: string;
  type: "PACKAGE_MODULE_WIDGET";
  parentId: string;
  renderMode: "CANVAS" | "PAGE";

  // 모듈 참조 (레지스트리 조회용)
  moduleUUID: string;
  packageUUID: string;

  // 인스턴스 식별
  moduleInstanceId: string;

  // 인스턴스별 데이터 (사용자가 설정한 값)
  inputs: Record<string, unknown>;

  // 위치/크기
  leftColumn: number;
  rightColumn: number;
  topRow: number;
  bottomRow: number;
}

/**
 * 레거시 구조: 전체 데이터 복사 (마이그레이션 대상)
 *
 * 기존에 페이지에 저장되던 전체 모듈 데이터입니다.
 * 이 구조가 감지되면 자동으로 새 구조로 마이그레이션됩니다.
 */
export interface ModuleWidgetPropsLegacy extends ModuleWidgetPropsNew {
  // 레거시 필드들 (마이그레이션 후 제거)
  moduleName: string;
  packageName: string;
  moduleInstanceData: {
    actions: ActionConfig[];
    jsObjects: ActionCollectionConfig[];
    inputsForm: ModuleInputSection[];
    outputsForm: ModuleOutputSection[];
  };
  moduleDSL: ModuleDSL;
  inputsForm: ModuleInputSection[];
  outputsForm: ModuleOutputSection[];
}

/**
 * 액션 실행 데이터
 */
export interface ActionExecutionData {
  isLoading: boolean;
  data: unknown;
  error?: string;
}

/**
 * JS 실행 데이터
 */
export interface JSExecutionData {
  [functionName: string]: {
    isLoading: boolean;
    data: unknown;
    error?: string;
  };
}

/**
 * 변환된 액션 (인스턴스 접두사 적용)
 */
export interface TransformedAction extends ActionConfig {
  originalName: string; // 원본 이름
  transformedName: string; // 변환된 이름: mod_xxx_QueryName
}

/**
 * 변환된 JS 컬렉션 (인스턴스 접두사 적용)
 */
export interface TransformedJSCollection extends ActionCollectionConfig {
  originalName: string;
  transformedName: string; // 변환된 이름: mod_xxx_JSObjectName
  transformedBody: string; // 내부 참조 변환된 코드
}

/**
 * 런타임 모듈 인스턴스 (Redux 상태)
 *
 * 페이지 로드 시 생성되어 Redux 상태에서 관리됩니다.
 */
export interface RuntimeModuleInstance {
  instanceId: string;
  moduleUUID: string;

  // 변환된 로직 (인스턴스 접두사 적용)
  actions: TransformedAction[];
  jsObjects: TransformedJSCollection[];

  // 스키마 (레지스트리에서 복사)
  inputsForm: ModuleInputSection[];
  outputsForm: ModuleOutputSection[];

  // 상태
  inputs: Record<string, unknown>;
  outputs: Record<string, unknown>;

  // 실행 데이터
  actionData: Record<string, ActionExecutionData>;
  jsData: Record<string, JSExecutionData>;
}

/**
 * 공통 데이터 + 인스턴스 데이터 병합 결과
 *
 * 페이지 렌더링 시 ModuleRegistry의 공통 데이터와
 * 페이지에 저장된 인스턴스 데이터를 병합한 결과입니다.
 */
export interface MergedModuleState {
  // 모듈 정의 참조
  moduleUUID: string;
  moduleName: string;
  packageUUID: string;
  packageName: string;

  // 인스턴스 정보
  instanceId: string;

  // 병합된 입력값 (인스턴스 값 우선, 없으면 기본값)
  inputs: Record<string, unknown>;

  // 변환된 DSL (인스턴스 접두사 적용)
  transformedDSL: ModuleDSL;

  // 변환된 액션/JS (인스턴스 접두사 적용)
  transformedActions: TransformedAction[];
  transformedJSObjects: TransformedJSCollection[];

  // 스키마 참조
  inputsForm: ModuleInputSection[];
  outputsForm: ModuleOutputSection[];
}

/**
 * 마이그레이션 필요 여부 판단
 *
 * @param props - 검사할 위젯 props
 * @returns moduleInstanceData가 존재하면 true (레거시 구조)
 */
export function needsModuleMigration(
  props: ModuleWidgetPropsNew | ModuleWidgetPropsLegacy,
): props is ModuleWidgetPropsLegacy {
  return (
    "moduleInstanceData" in props && props.moduleInstanceData !== undefined
  );
}

/**
 * Redux 액션 타입
 */
export const MODULE_INSTANCE_ACTIONS = {
  REGISTER: "REGISTER_MODULE_INSTANCE",
  UNREGISTER: "UNREGISTER_MODULE_INSTANCE",
  UPDATE_INPUTS: "UPDATE_MODULE_INSTANCE_INPUTS",
  UPDATE_OUTPUTS: "UPDATE_MODULE_INSTANCE_OUTPUTS",
  SET_ACTION_DATA: "SET_MODULE_INSTANCE_ACTION_DATA",
  SET_JS_DATA: "SET_MODULE_INSTANCE_JS_DATA",
} as const;

/**
 * 모듈 인스턴스 등록 페이로드
 */
export interface RegisterModuleInstancePayload {
  instanceId: string;
  moduleUUID: string;
  actions: TransformedAction[];
  jsObjects: TransformedJSCollection[];
  inputsForm: ModuleInputSection[];
  outputsForm: ModuleOutputSection[];
  inputs: Record<string, unknown>;
}

/**
 * 모듈 입력값 업데이트 페이로드
 */
export interface UpdateModuleInputsPayload {
  instanceId: string;
  inputs: Record<string, unknown>;
}
