import type { WidgetCardProps } from "widgets/BaseWidget";

/**
 * Package JSON 파일의 전체 구조
 */
export interface PackageJSON {
  artifactJsonType: "PACKAGE";
  clientSchemaVersion: number;
  serverSchemaVersion: number;
  exportedPackage: ExportedPackage;
  datasourceList: DatasourceConfig[];
  moduleList: ModuleConfig[];
  actionList: ActionConfig[];
  actionCollectionList: ActionCollectionConfig[];
}

/**
 * 패키지 정보
 */
export interface ExportedPackage {
  packageUUID: string;
  type: "UI" | "QUERY" | "JS";
  unpublishedPackage: {
    name: string;
    icon: string;
    color: string;
  };
  deleted: boolean;
}

/**
 * 데이터소스 설정
 */
export interface DatasourceConfig {
  datasourceConfiguration: {
    connection: {
      mode: string;
      ssl: { authType: string };
    };
    endpoints: Array<{ host: string; port: number }>;
  };
  name: string;
  pluginId: string;
  messages: string[];
  isAutoGenerated: boolean;
  isTemplate: boolean;
  gitSyncId: string;
  deleted: boolean;
}

/**
 * 모듈 설정
 */
export interface ModuleConfig {
  type: "UI_MODULE" | "QUERY_MODULE" | "JS_MODULE";
  moduleUUID: string;
  unpublishedModule: {
    name: string;
    inputsForm: ModuleInputSection[];
    outputsForm: ModuleOutputSection[];
    layouts: ModuleLayout[];
  };
  gitSyncId: string;
  deleted: boolean;
}

/**
 * 모듈 Input 정의
 * 페이지에서 모듈에 전달하는 파라미터
 *
 * 실제 JSON 구조:
 * {
 *   "id": "bzkrhnmnap",
 *   "label": "defaultSelected",  // input 이름
 *   "propertyName": "inputs.defaultSelected",
 *   "controlType": "INPUT_TEXT",
 *   "defaultValue": "[]"
 * }
 */
export interface ModuleInputDefinition {
  id: string;
  label: string; // input 이름 (예: "defaultSelected", "label", "disabled")
  name?: string; // 대체 이름 필드 (호환성)
  propertyName?: string; // "inputs.defaultSelected" 형태
  controlType?: string; // "INPUT_TEXT", "SWITCH" 등
  defaultValue: unknown;
  type?: "string" | "number" | "boolean" | "array" | "object";
}

export interface ModuleInputSection {
  id: string;
  sectionName: string;
  children: ModuleInputDefinition[];
}

/**
 * 모듈 Output 정의
 * 모듈에서 페이지로 노출하는 데이터
 *
 * 실제 JSON 구조:
 * {
 *   "id": "kjtucgtyfb",
 *   "label": "selectedMember",  // output 이름
 *   "propertyName": "outputs.selectedMember",
 *   "value": "{{MultiSelect1.selectedOptionValues}}"
 * }
 */
export interface ModuleOutputDefinition {
  id: string;
  label: string; // output 이름
  name?: string; // 대체 이름 필드 (호환성)
  propertyName?: string; // "outputs.selectedMember" 형태
  value: string; // 바인딩 표현식, 예: "{{MultiSelect1.selectedOptionValues}}"
}

export interface ModuleOutputSection {
  id: string;
  sectionName: string;
  children: ModuleOutputDefinition[];
}

/**
 * 모듈 인스턴스의 Input/Output 런타임 값
 */
export interface ModuleInstanceInputs {
  [inputName: string]: unknown;
}

export interface ModuleInstanceOutputs {
  [outputName: string]: unknown;
}

export interface ModuleLayout {
  viewMode: boolean;
  dsl: ModuleDSL;
  layoutOnLoadActions: LayoutOnLoadAction[][];
  layoutOnLoadActionErrors: unknown[];
  validOnPageLoadActions: boolean;
  id: string;
  deleted: boolean;
  policies: unknown[];
  userPermissions: unknown[];
}

/**
 * 모듈 DSL (위젯 트리)
 */
export interface ModuleDSL {
  widgetName: string;
  type: string;
  widgetId: string;
  children?: ModuleDSL[];
  [key: string]: unknown;
}

export interface LayoutOnLoadAction {
  id: string;
  name: string;
  confirmBeforeExecute: boolean;
  pluginType: string;
  jsonPathKeys: string[];
  timeoutInMillisecond: number;
}

/**
 * 액션 설정 (Query, JS 함수 등)
 */
export interface ActionConfig {
  isPublic: boolean;
  pluginType: "DB" | "JS";
  pluginId: string;
  unpublishedAction: {
    moduleId: string;
    name: string;
    fullyQualifiedName?: string;
    datasource: {
      name: string;
      pluginId: string;
      messages: string[];
      isAutoGenerated: boolean;
      id?: string;
      deleted: boolean;
      policyMap: Record<string, unknown>;
      policies: unknown[];
      userPermissions: unknown[];
    };
    contextType: "MODULE";
    collectionId?: string;
    actionConfiguration: {
      timeoutInMillisecond: number;
      paginationType: string;
      encodeParamsToggle: boolean;
      body: string;
      selfReferencingDataPaths: string[];
      pluginSpecifiedTemplates?: Array<{ value: boolean }>;
      jsArguments?: unknown[];
    };
    runBehaviour: "AUTOMATIC" | "MANUAL";
    dynamicBindingPathList: Array<{ key: string }>;
    isValid: boolean;
    invalids: string[];
    messages: string[];
    jsonPathKeys: string[];
    userSetOnLoad: boolean;
    confirmBeforeExecute: boolean;
    policyMap: Record<string, unknown>;
    userPermissions: unknown[];
    createdAt: string;
  };
  publishedAction: {
    messages: string[];
    userSetOnLoad: boolean;
    confirmBeforeExecute: boolean;
    policyMap: Record<string, unknown>;
    userPermissions: unknown[];
  };
  gitSyncId: string;
  id: string;
  deleted: boolean;
}

/**
 * JS Object 컬렉션 설정
 */
export interface ActionCollectionConfig {
  isPublic: boolean;
  unpublishedCollection: {
    moduleId: string;
    name: string;
    contextType: "MODULE";
    pluginId: string;
    pluginType: "JS";
    actions: unknown[];
    archivedActions: unknown[];
    body: string;
    variables: unknown[];
    userPermissions: unknown[];
  };
  gitSyncId: string;
  id: string;
  deleted: boolean;
}

/**
 * UI 사이드바에 표시될 모듈 카드 (WidgetCardProps 확장)
 */
export interface PackageModuleCard extends WidgetCardProps {
  moduleUUID: string;
  packageUUID: string;
  packageName: string;
  moduleName: string;
  moduleType: "UI_MODULE" | "QUERY_MODULE" | "JS_MODULE";
  dsl: ModuleDSL;
  actions: ActionConfig[];
  actionCollections: ActionCollectionConfig[];
  datasources: DatasourceConfig[];
  // Input/Output 정의
  inputsForm?: ModuleInputSection[];
  outputsForm?: ModuleOutputSection[];
}

/**
 * 패키지별로 그룹화된 모듈 목록
 */
export interface PackageGroup {
  packageUUID: string;
  packageName: string;
  packageIcon: string;
  packageColor: string;
  modules: PackageModuleCard[];
}

/**
 * 모듈 인스턴스 (캔버스에 배치된 모듈)
 */
export interface ModuleInstance {
  instanceId: string;
  moduleUUID: string;
  packageUUID: string;
  moduleName: string;
  dsl: ModuleDSL;
  actions: ActionConfig[];
  actionCollections: ActionCollectionConfig[];
  isReadOnly: boolean;
  // Input/Output 정의
  inputsForm?: ModuleInputSection[];
  outputsForm?: ModuleOutputSection[];
  // 런타임 Input/Output 값
  inputs?: ModuleInstanceInputs;
  outputs?: ModuleInstanceOutputs;
}

/**
 * 모듈 위젯 타입 상수
 */
export const PACKAGE_MODULE_WIDGET_TYPE = "PACKAGE_MODULE_WIDGET";

/**
 * 기본 모듈 카드 속성
 */
export const DEFAULT_MODULE_CARD_PROPS = {
  rows: 40,
  columns: 24,
  icon: "package",
} as const;
